---
- name: Deploying the application
  hosts: all
  tasks: 
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Copy docker compose file
      become: false
      copy:
        src: ./docker-compose.yml
        dest: ./
        owner: ubuntu
        group: ubuntu
        mode: 0777
    
    - name: Start the application
      shell: docker-compose up
