version: "3.8"
services:
  frontend:
    image: ashu07soni/final_frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - final_project
    depends_on:
      - backend

  backend:
    image: ashu07soni/final_backend
    container_name: backend
    ports:
      - "9090:9090"
    networks:
      - final_project
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql/mysql-server
    container_name: mysql
    networks:
      - final_project
    environment:
      - MYSQL_ROOT_PASSWORD=Ashu@0710
      - MYSQL_DATABASE=spe_project
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Ashu@0710

networks:
  final_project:
